"""initial SaaS schema

Revision: e094ab60ff70
Revises:
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "e094ab60ff70"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("google_sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_google_sub"), ["google_sub"], unique=True)

    op.create_table(
        "workspaces",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stripe_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("billing_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("billing_event_at", sa.Integer(), nullable=False),
        sa.Column("ai_profiles", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_customer_id"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interview_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("error_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_interview_id"), ["interview_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_runs_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "interviews",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("started_at", sa.Float(), nullable=True),
        sa.Column("ended_at", sa.Float(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lock_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lock_until", sa.Float(), nullable=False),
        sa.Column("job_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("job_description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("custom_instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("persona", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resume_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resume_snapshot", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("ai_profiles", sa.JSON(), nullable=False),
        sa.Column("current_topic", sa.Integer(), nullable=False),
        sa.Column("followup_count", sa.Integer(), nullable=False),
        sa.Column("closing_remark", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interviews_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_interviews_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interviews_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "invitations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("accepted_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invitations_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("csrf_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("login_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memberships",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "user_id"),
    )
    op.create_table(
        "resumes",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mime", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("candidate_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_resumes_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_resumes_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "usage_buckets",
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("workspace_id", "period", "resource"),
    )
    op.create_table(
        "agent_jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interview_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=False),
        sa.Column("available_at", sa.Float(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id"),
    )
    with op.batch_alter_table("agent_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_agent_jobs_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "operations",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interview_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id", "request_id"),
    )
    with op.batch_alter_table("operations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_operations_interview_id"), ["interview_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_operations_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "practice_tasks",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interview_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instructions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("skill", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Float(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("practice_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_practice_tasks_interview_id"), ["interview_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_practice_tasks_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_practice_tasks_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "turns",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interview_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("assessment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id", "position"),
    )
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_turns_interview_id"), ["interview_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_turns_workspace_id"), ["workspace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_turns_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_turns_interview_id"))

    op.drop_table("turns")
    with op.batch_alter_table("practice_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_practice_tasks_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_practice_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_practice_tasks_interview_id"))

    op.drop_table("practice_tasks")
    with op.batch_alter_table("operations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operations_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_operations_interview_id"))

    op.drop_table("operations")
    with op.batch_alter_table("agent_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_jobs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_jobs_status"))

    op.drop_table("agent_jobs")
    op.drop_table("usage_buckets")
    with op.batch_alter_table("resumes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resumes_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_resumes_user_id"))

    op.drop_table("resumes")
    op.drop_table("memberships")
    with op.batch_alter_table("login_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_login_sessions_expires_at"))

    op.drop_table("login_sessions")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_workspace_id"))

    op.drop_table("invitations")
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interviews_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_interviews_user_id"))
        batch_op.drop_index(batch_op.f("ix_interviews_created_at"))

    op.drop_table("interviews")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_workspace_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_user_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_interview_id"))
        batch_op.drop_index(batch_op.f("ix_agent_runs_created_at"))

    op.drop_table("agent_runs")
    op.drop_table("workspaces")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_google_sub"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("billing_events")
    # ### end Alembic commands ###
